# Generated by Django 5.1.4 on 2026-08-19 05:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField(blank=True)),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None)),
                ('benefits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None)),
                ('screenshots', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None)),
                ('pricing', models.CharField(blank=True, help_text="e.g. 'From KES 15,000'", max_length=120)),
                ('pricing_type', models.CharField(choices=[('one_time', 'One-time'), ('monthly', 'Monthly'), ('annual', 'Annual'), ('custom', 'Custom Quote'), ('free', 'Free')], default='custom', max_length=20)),
                ('demo_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('beta', 'Beta'), ('available', 'Available'), ('coming_soon', 'Coming Soon'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, default=list, size=None)),
                ('integrations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, default=list, size=None)),
                ('faqs', models.JSONField(blank=True, default=list, help_text='List of {"question": "...", "answer": "..."}')),
                ('target_customer', models.CharField(blank=True, max_length=200)),
                ('problem_solved', models.TextField(blank=True)),
                ('how_it_works', models.TextField(blank=True)),
                ('security_notes', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industries', models.ManyToManyField(blank=True, related_name='products', to='cms.industry')),
                ('testimonials', models.ManyToManyField(blank=True, related_name='products', to='cms.testimonial')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
