# Generated by Django 5.1.4 on 2026-08-19 06:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='/', max_length=500)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('device', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], default='desktop', max_length=20)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['viewed_at'], name='dashboard_a_viewed__20a493_idx'), models.Index(fields=['path'], name='dashboard_a_path_26e433_idx')],
            },
        ),
    ]
