# Generated by Django 5.1.4 on 2026-08-19 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('path', models.CharField(blank=True, default='', max_length=500)),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='dashboard_a_created_fb7b78_idx'), models.Index(fields=['action'], name='dashboard_a_action_86d6c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('path', models.CharField(default='/', max_length=500)),
                ('device', models.CharField(default='desktop', max_length=20)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('entered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_active_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-last_active_at'],
                'indexes': [models.Index(fields=['last_active_at'], name='dashboard_p_last_ac_26dc0b_idx'), models.Index(fields=['path'], name='dashboard_p_path_b399c3_idx')],
                'constraints': [models.UniqueConstraint(fields=('session_key', 'path'), name='uniq_page_session')],
            },
        ),
        migrations.CreateModel(
            name='SectionEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('path', models.CharField(default='/', max_length=500)),
                ('section', models.CharField(default='', max_length=120)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=1)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_active_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_active_at'],
                'indexes': [models.Index(fields=['path', 'section'], name='dashboard_s_path_28883a_idx')],
                'constraints': [models.UniqueConstraint(fields=('session_key', 'path', 'section'), name='uniq_section_engagement')],
            },
        ),
    ]
