# Generated by Django 5.1.4 on 2026-08-20 08:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_activitylog_pagesession_sectionengagement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('replied', 'Replied'), ('archived', 'Archived'), ('unarchived', 'Unarchived'), ('marked_read', 'Marked read'), ('marked_unread', 'Marked unread'), ('uploaded', 'Uploaded')], default='created', max_length=30)),
                ('resource', models.CharField(blank=True, default='', max_length=60)),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, default='', max_length=400)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='dashboard_a_created_6fe503_idx'), models.Index(fields=['action'], name='dashboard_a_action_63331f_idx'), models.Index(fields=['resource'], name='dashboard_a_resourc_d7ea46_idx')],
            },
        ),
    ]
