# Generated by Django 5.1.4 on 2026-08-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_adminaudit_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaudit',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('replied', 'Replied'), ('archived', 'Archived'), ('unarchived', 'Unarchived'), ('marked_read', 'Marked read'), ('marked_unread', 'Marked unread'), ('uploaded', 'Uploaded'), ('sent_test', 'Sent test email'), ('sent_telegram', 'Sent Telegram message')], default='created', max_length=30),
        ),
    ]
