# Generated by Django 5.1.4 on 2026-08-19 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('need', models.CharField(blank=True, choices=[('ai', 'AI'), ('cybersecurity', 'Cybersecurity'), ('website', 'Website'), ('mobile_app', 'Mobile App'), ('enterprise_system', 'Enterprise System'), ('automation', 'Automation'), ('digital_transformation', 'Digital Transformation'), ('product', 'Product'), ('other', 'Other')], max_length=40)),
                ('budget_range', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('contact_form', 'Contact Form'), ('demo_request', 'Demo Request'), ('quote_request', 'Quote Request'), ('newsletter', 'Newsletter'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone'), ('email', 'Email')], default='contact_form', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('meeting_scheduled', 'Meeting Scheduled'), ('demo', 'Demo'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('lead_score', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
