# Generated by Django 5.1.4 on 2026-08-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
