# Generated by Django 5.1.4 on 2026-08-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_is_archived_lead_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='lead',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('contact_form', 'Contact Form'), ('demo_request', 'Demo Request'), ('quote_request', 'Quote Request'), ('newsletter', 'Newsletter'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('phone', 'Phone'), ('email', 'Email')], default='contact_form', max_length=20),
        ),
    ]
