# Generated by Django 5.1.4 on 2026-08-19 05:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('ai-automation', 'AI & Automation'), ('cybersecurity', 'Cybersecurity'), ('software-engineering', 'Software Engineering'), ('digital-transformation', 'Digital Transformation'), ('data-intelligence', 'Data & Intelligence')], max_length=40)),
                ('short_description', models.TextField()),
                ('hero_text', models.TextField(blank=True)),
                ('problem', models.TextField(blank=True)),
                ('approach', models.TextField(blank=True)),
                ('capabilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None)),
                ('use_cases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None)),
                ('benefits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None)),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, default=list, size=None)),
                ('faqs', models.JSONField(blank=True, default=list, help_text='List of {"question": "...", "answer": "..."}')),
                ('image', models.ImageField(blank=True, null=True, upload_to='solutions/')),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('cta_text', models.CharField(blank=True, default='Talk to Florante', max_length=120)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
