# Generated by Django 5.1.4 on 2026-08-19 05:05

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('author_name', models.CharField(blank=True, max_length=150)),
                ('author_role', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('ai', 'AI'), ('cybersecurity', 'Cybersecurity'), ('african-technology', 'African Technology'), ('software-engineering', 'Software Engineering'), ('digital-transformation', 'Digital Transformation'), ('business-technology', 'Business Technology'), ('education-technology', 'Education Technology')], default='african-technology', max_length=40)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=list, size=None)),
                ('featured_image', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('client', models.CharField(max_length=200)),
                ('challenge', models.TextField(blank=True)),
                ('existing_situation', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('technologies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, default=list, size=None)),
                ('implementation', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('client_quote', models.TextField(blank=True)),
                ('client_quote_author', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='case-studies/')),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('seo_description', models.TextField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='cms.industry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
